### ISSUE TITLE
Create navigation component

### ISSUE THREAD

**Issue by MBrunoS** [forjadev/mjo-forja-webpage#5]
Description:
Our webapp has a navigation component, like the example below.
Please use a semantic HTML, I suggest to use HTML tags like nav, ul and li, the selected nav item should be highlighted like the image.

![Image](https://user-images.githubusercontent.com/64755624/255736505-c351adaa-a0d5-4b2c-88cf-d349a8bcc756.png)
figma: https://www.figma.com/file/PnSE4hrYIAkDgPPjVRxAUV/Landing-Page?type=design&node-id=356-341&mode=design&t=MmjRDGGDwGTDFmFB-0

Acceptance Criteria:
Should be able to see Navigation component on Storybook

**Comment by kevinCubas** [comment]
Guys, to follow the Project's component exporting pattern, I'm creating an index file at the root of the Components folder to export our components.

**Comment by kevinCubas** [comment]
Updates on my progress with this issue. I've made some improvements:

1. I went through the code and removed any unnecessary Tailwind classes. This helps reduce the overall bundle size and improves performance. Even though Tailwind does it natively.

2. I've modified some styles to ensure the component achieves a pixel-perfect layout.

3. Instead of passing a `children` React node as props, I created a new interface. Now, when using the component, we need to pass the following props:
   - `textPrimary` (required).
   - `textSecondary` (optional): This prop is optional and represents the "PRO" text, but now we can also test with other words without rewriting styles.
   - `href` (required)
   - `isActive` (optional)
4. To follow the project's component exporting pattern, as I said before I'd create an index file under the components folder to export our components.

By using this new interface, it becomes simpler to add the component to Storybook, and it helps prevent errors when passing props.

Let me know if you have any questions or feedback.

**Comment by MBrunoS** [comment]
Great! But on the 3rd point, I think that using two props like this wouldn't be "scalable". For example, if we needed later a nav item with the highlighted word in the middle, we'd need to change the component.

And I understand what you said about being simpler to add on Storybook, it really is. But SB also let us do components composition: https://storybook.js.org/tutorials/intro-to-storybook/react/en/composite-component/

I am making sense?

**Comment by kevinCubas** [comment]
> Great! But on the 3rd point, I think that using two props like this wouldn't be "scalable". For example, if we needed later a nav item with the highlighted word in the middle, we'd need to change the component.
> 
> And I understand what you said about being simpler to add on Storybook, it really is. But SB also let us do components composition: https://storybook.js.org/tutorials/intro-to-storybook/react/en/composite-component/
> 
> I am making sense?

Yeah, it does make sense. I'll you try another approach to make it more scalable. Thanks for the feedback! 🚀

**Comment by kevinCubas** [comment]
I'm creating the component's stories today

**Comment by kevinCubas** [comment]
As the design changed, I made some improvements to the components and stories, as well as create the DropdownMenu mobile.
